---
- name: IP2
  hosts: all
  become: true
  become_user: root
  gather_facts: true
  connection: ssh
  tasks: 
    - name: "install apache"
      package: name=apache2 state=present
    - name: "git"
      package: name=git state=present
    - name: "curl"
      package: name=curl state=present

